### ISSUE TITLE
Translated into Traditional Chinese

### ISSUE THREAD

**Issue by Kevin28576** [ncase/wbwwb#53]
Hey great author
I translated all the text, including images, of this little game into Traditional Chinese, and below is where I ended up hosting it.

[https://io.cloudxact.com/ncase/wbwwb/](https://io.cloudxact.com/ncase/wbwwb/)

**Comment by ncase** [comment]
Thank you so much @Kevin28576 ! 🎉 (Sorry for the very late reply!)  I've added your link to the description of the game here on Itch: https://ncase.itch.io/wbwwb

<img width="587" alt="Screen Shot 2024-01-15 at 15 50 10" src="https://github.com/ncase/wbwwb/assets/825858/2ba28b5a-c2c3-45d4-8adc-c177d5ebb41d">

Happy new year 2024!
