### ISSUE TITLE
Stuck at 82%

### ISSUE THREAD

**Issue by Wishdog2013** [ncase/wbwwb#55]
been here for like 3 minutes
![image](https://github.com/ncase/wbwwb/assets/100239673/db826337-b2d6-4ca6-99d7-520f52bbe6c8)
this doesnt look good either 
![image](https://github.com/ncase/wbwwb/assets/100239673/e04671fb-cc3d-48c2-ac9c-5d870eb05ead)
but idk much about web games lol

**Comment by Wishdog2013** [comment]
actually nvm it works on Microsoft Edge

**Comment by Exnonull** [comment]
reported solution in https://github.com/ncase/wbwwb/issues/58
